project:
  type: book

book:
  title: "Fuerzas: Fichas"
  author: "David Domínguez Román"
  date: "4/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - ficha1.qmd
    - ficha2.qmd
    - ficha3.qmd
    - ficha4.qmd
    - ficha5.qmd
    - sitaprs1.qmd
    - sitaprs2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mainfont: "Arial"
    fontsize: "12"
    monofont: "JetBrains Mono"
    lightbox: true
    execute:
      enable: true
      echo: false


