---
title: "Fuerzas: tipos de fuerzas y tipos de cuerpos (extra)"
---

Nombre:\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Lee con detenimiento los enunciados**

------------------------------------------------------------------------

------------------------------------------------------------------------

**1.-** Cuando sujetas un libro **has de aplicar una fuerza**. Sin embargo, **no cambia su estado de movimiento ni se deforma**. ¿Qué crees que está pasando? **Haz un dibujo**

<br>

<br>

<br>

<br>

<br>

<br>

<br>

<br>

<br>

<br>

**2.-** **Clasifica** los siguientes objetos en rígidos, plásticos o elásticos:

-   Un libro:

-   Una miga de pan:

-   Una goma elástica:

-   Una guitarra:

-   Un bloque de cemento:

-   Una taza:

-   Un bote de cristal:

<br>

**3.-** Una moto entra en una rotonda. ¿Crees que **aparecen fuerzas** para que la moto gire?

<br>

<br>

**4.-** ¿Cuáles de estas fuerzas son **a distancia** o **por contacto**?

-   Apoyar un boli en la mesa:

-   La caída de una piedra desde un puente:

-   Sentarse en la silla:

-   El movimiento de un tren por levitación magnética:

<br>

**5.-** **Rodea con un círculo** aquella unidad que se utilice para **medir la fuerza**:

|           |     |
|-----------|-----|
| Kilogramo | kg  |
| Julio     | J   |
| Newton    | N   |
| Culombio  | C   |

<br>

<br>

<br>


**6.-** Las varillas de cocina suelen estar hechas de acero y se utilizan para batir. ¿Qué tipo de material es el acero: rígido, elástico o plástico?

<br>

**7.-** **Dos personas tiran de una caja**, una con una fuerza de 200N y otra con una fuerza **en sentido contrario** de 300N. **Haz un dibujo** de la situación y **calcula la fuerza resultante.**

<br>

<br>

<br>

<br>